"""unique constraint for city and datetime

Revision ID: 83323d7d22ab
Revises: eff0868cb82e
Create Date: 2025-07-05 22:51:01.513282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83323d7d22ab'
down_revision: Union[str, Sequence[str], None] = 'eff0868cb82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temperature') as batch_op:
        batch_op.create_unique_constraint('uix_city_date', ['city_id', 'date_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temperature') as batch_op:
        batch_op.drop_constraint('uix_city_date', type_='unique')
    # ### end Alembic commands ###
